### ISSUE TITLE
Sicherheitslücke in Github Workflow schließen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.os.github.workflows#11]
Meldung von Dependabot: tj-actions/branch-names's Improper Sanitization of Branch Name Leads to Arbitrary Code Injection

Die Meldung ist zuerst im RCP Repository aufgetaucht:
https://github.com/minova-afis/aero.minova.rcp/security/dependabot/1

Es sind aber auch die allgemeinen Workflows und somit fast alle neuen Repositories betroffen:
https://github.com/minova-afis/aero.minova.os.github.workflows/security/dependabot/1

Ein Update auf Version 7.0.7 scheint das Problem zu lösen, allerdings wird dieses von Dependabot nicht vorgeschlagen.

Abrechnung={MIN/Intern-MIN/NETZ/ZWARTUNG}

**Comment by scholz-afis** [comment]
Habe die neue Version in den Workflows auf @main und Java 21c eingetragen. Die [Security-Warnungen](https://github.com/minova-afis/aero.minova.os.github.workflows/security/dependabot?q=is%3Aclosed) haben sich selbständif wieder geschlossen. 
@janiak-minova: Bitte reviewen.

**Comment by janiak-minova** [comment]
Ich bin über die Suche auch mal die anderen Repos durchgegangen und habe die Version erhöht (außer bei archivierten Repos).
https://github.com/search?q=org%3Aminova-afis+tj-actions%2Fbranch-names&type=code

Ich denke damit haben wir alle relevanten Vorkommen erwischt.
